### PR TITLE
task1 - image processing - Sukrit Bhattacharya

### PR DESCRIPTION
**Pull request by sukritbhattacharya**

### CODE REVIEW

**Comment by pushkalkatara** [comment]
Couldn't find the ROS Task. Also, couldn't find the labelled images.

**Comment by HarshitNagar** [comment]
Couldn't find the ROS Task. Also, couldn't find the labelled images....again

**Comment by sukritbhattacharya** [comment]
Data labelling task uploaded

**Comment by HarshitNagar** [comment]
alright.

**Comment by pushkalkatara** [comment]
@sukrit4498 The code won't work, please check again.

**Pull request merged**
