### PR TITLE
Create 3_labelling

### PR DESCRIPTION
**Pull request by abhishek2000123**
[3_labels.zip](https://github.com/srmauvsoftware/recruit-tasks/files/2408004/3_labels.zip)

### CODE REVIEW

**Comment by HarshitNagar** [comment]
did you read the instructions carefully?    
you have labelled path_v, path_h, path', labelled the reflections (it was told not to do so in the instructions), labelled the swimming pool tiles as the path' (there was even a doubt posted on the group asking if those tiles were paths or not)

**Comment by abhishek2000123** [comment]
Reflections I don't remember labelling reflections. CN you send me an example pic

**Comment by abhishek2000123** [comment]
So am I expected to do 351 images all over again they are only slight errors

**Comment by abhishek2000123** [comment]
[3_labels1.zip](https://github.com/srmauvsoftware/recruit-tasks/files/2408764/3_labels1.zip)

**Comment by HarshitNagar** [comment]
alright.

**Pull request merged**
